[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments.production]
variables = { }

[environments.production.build]
buildCommand = "pip install -r requirements.txt"

[environments.production.deploy]
startCommand = "python start.py"