[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { }

[environments.production.build]
buildCommand = "echo 'Build completed'"

[environments.production.deploy]
startCommand = "uvicorn backend.main_cloud:app --host 0.0.0.0 --port $PORT"