[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments.production]
variables = { }

[environments.production.build]
buildCommand = "pip install -r requirements.txt"

[environments.production.deploy]
startCommand = "uvicorn backend.main_cloud:app --host 0.0.0.0 --port ${PORT:-8080}"